### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by dmarks2**
Hey @jtydhr88,

here are some Unit Tests for my code completion features. I already found some issues (acutally NullPointerExceptions) by running my tests, so I fixed them to make my tests "green".

### CODE REVIEW

**Comment by jtydhr88** [comment]
hey @dmarks2, I made some changes for definition files in https://github.com/gamerson/liferay-intellij-plugin/pull/46, I will review your changes after it merged.

**Comment by jtydhr88** [comment]
sent to Greg, thanks.

**Comment by dmarks2** [comment]
Hey @jtydhr88,

do you know if https://issues.liferay.com/projects/INTELLIJ/issues/INTELLIJ-11 is still a problem?

In my opinion the issue should have been fixed already by this commit (which was part of this pull request):

https://github.com/liferay/liferay-intellij-plugin/commit/49fdeb0608c63e043ee30c736269fb4ee3f0bad7

Regards, 
 Dominik

**Comment by jtydhr88** [comment]
hey @dmarks2, I keep it as we may add more tests and we can reuse it.

**Comment by jtydhr88** [comment]
It seems nobody meet it at all, I will close it soon, thanks.

**Pull request closed without merging**
