### PR TITLE
INTELLIJ-1 Add Liferay frontend development support

### PR DESCRIPTION
**Pull request by dmarks2**
Hey @jtydhr88,

here is my implementation to add predefined JavaScript libraries to the IntelliJ plugin. By this, code completion for all the Liferay Javascripts should work.

Note that there is an open issue in IntelliJ 2018.3.x which causes that code completion for custom Javascript libraries does not work inside `<script>`-Tags inside JSPs. Nevertheless it works properly in Javascript-Files (.js) and inside the custom tag `<aui:script>`. See ticket here: https://youtrack.jetbrains.com/issue/WEB-37355

### CODE REVIEW

**Comment by jtydhr88** [comment]
hey @dmarks2, thanks for the contribution!
Now we enable Target Platform for Liferay workspace by default, therefore we could assume there must be target platform existing, which means we read lib jar information from it.
You could see the wizard of Module Ext, there is a list of all dependencies from current target platform.
I know we could use this way rather than downloading online.
Let me know if you have questions for it.

**Comment by jtydhr88** [comment]
And for the users who do not config the target platform...I think it is ok that just prompt them to config to support this feature.

**Comment by dmarks2** [comment]
Hey @jtydhr88,

thank you for your Feedback. I will have a look at the "Target Platform" and see if I can load the Javascript files from those libraries.

**Comment by dmarks2** [comment]
@jtydhr88 I changed the implementation so that it looks at the "Target Platform" and loads the Javascript files from there. 

It seems that the "Target Platform" functionality is available for Gradle projects, only? Are there any plans to support Maven projects, too?

**Comment by jtydhr88** [comment]
Hey, thanks for your work!
Yes, we have plan to make target platform support for Maven, you can see here:
https://github.com/gamerson/liferay-portal/pull/257

**Comment by jtydhr88** [comment]
We could add Maven support once the target platform for Maven finishing.

**Comment by jtydhr88** [comment]
hey @dmarks2, as I am busy on the other project, I'd like to introduce @seiphon to help me doing review work firstly, @seiphon please feel free to leave your question about it.

**Comment by jtydhr88** [comment]
Sent to Greg, thanks.

**Pull request closed without merging**
