### PR TITLE
Code Completion for resource bundle keys for Liferay Taglibs (#59)

### PR DESCRIPTION
**Pull request by dmarks2**
I would like to contribute a ReferenceContributor for resource bundle keys in Liferay Taglibs. Many attributes can refer to keys inside the language files.

IntelliJ will suggest keys from available Language_XX.properties files for attributes like <liferay-ui:message key="..." />. It is possible to search for usage of those keys (Alt-F7) and to rename the keys on the fly (Shift-F6).

### CODE REVIEW

**Comment by jtydhr88** [comment]
hey @dmarks2, thanks for your code and see my screenshot
r1
now it seems your code will load all of "properties" files whether the name is and the location is.
is that possible that only use "resource bundle" files?

**Comment by dmarks2** [comment]
Hello @jtydhr88,

I have updated my code to look at property files starting with "Language", only (e.g. Language.properties, Language_en.properties and so on.) 

I reproduced your test case and now it only shows the properties from the resource bundles and not from pp.properties or mm.properties.

**Comment by jtydhr88** [comment]
sent to Greg, thanks a lot

**Comment by dmarks2** [comment]
Thanks @jtydhr88, should I send future pull requests to you instead of Greg?

**Comment by jtydhr88** [comment]
yes, please do it and I will send to Greg then

**Pull request closed without merging**
